const juegos = {
    "Shooter": [
      {
        "id": 310,
        "title": "Team Fortress 2",
        "thumbnail": "https://www.freetogame.com/g/310/thumbnail.jpg",
        "short_description": "Valve's iconic class-based free-to-play first-person shooter!",
        "game_url": "https://www.freetogame.com/open/team-fortress-2",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "Valve",
        "developer": "Valve",
        "release_date": "2007-10-10",
        "freetogame_profile_url": "https://www.freetogame.com/team-fortress-2"
      },
      {
        "id": 15,
        "title": "Crossfire",
        "thumbnail": "https://www.freetogame.com/g/15/thumbnail.jpg",
        "short_description": "A first person tactical shooter with a huge selection of game modes!",
        "game_url": "https://www.freetogame.com/open/crossfire",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "Neowiz Games",
        "developer": "SmileGate",
        "release_date": "2007-05-03",
        "freetogame_profile_url": "https://www.freetogame.com/crossfire"
      },
      {
        "id": 313,
        "title": "Teeworlds",
        "thumbnail": "https://www.freetogame.com/g/313/thumbnail.jpg",
        "short_description": "A free to play retro multiplayer online shooter where you can even design your own maps!",
        "game_url": "https://www.freetogame.com/open/teeworlds",
        "genre": "Shooter",
        "platform": "PC (Windows)",
        "publisher": "Teeworlds Team ",
        "developer": "Teeworlds Team ",
        "release_date": "2007-05-27",
        "freetogame_profile_url": "https://www.freetogame.com/teeworlds"
      }
    ],
    "MMOARPG": [
      {
        "id": 521,
        "title": "Diablo Immortal",
        "thumbnail": "https://www.freetogame.com/g/521/thumbnail.jpg",
        "short_description": "Built for mobile and also released on PC, Diablo Immortal fills in the gaps between Diablo II and III in an MMOARPG environment.",
        "game_url": "https://www.freetogame.com/open/diablo-immortal",
        "genre": "MMOARPG",
        "platform": "PC (Windows)",
        "publisher": "Blizzard Entertainment",
        "developer": "Blizzard Entertainment",
        "release_date": "2022-06-02",
        "freetogame_profile_url": "https://www.freetogame.com/diablo-immortal"
      }
    ],
    "ARPG": [
      {
        "id": 517,
        "title": "Lost Ark",
        "thumbnail": "https://www.freetogame.com/g/517/thumbnail.jpg",
        "short_description": "Smilegate’s free-to-play multiplayer ARPG is a massive adventure filled with lands waiting to be explored, people waiting to be met, and an ancient evil waiting to be destroyed.",
        "game_url": "https://www.freetogame.com/open/lost-ark",
        "genre": "ARPG",
        "platform": "PC (Windows)",
        "publisher": "Amazon Games",
        "developer": "Smilegate RPG",
        "release_date": "2022-02-11",
        "freetogame_profile_url": "https://www.freetogame.com/lost-ark"
      }
    ],
    "Strategy": [
      {
        "id": 425,
        "title": "Grepolis",
        "thumbnail": "https://www.freetogame.com/g/425/thumbnail.jpg",
        "short_description": "A free to play browser-based strategy MMORTS set in Ancient Greece.",
        "game_url": "https://www.freetogame.com/open/grepolis",
        "genre": "Strategy",
        "platform": "Web Browser",
        "publisher": "InnoGames",
        "developer": "InnoGames",
        "release_date": "2009-12-08",
        "freetogame_profile_url": "https://www.freetogame.com/grepolis"
      },
      {
        "id": 428,
        "title": "Ikariam",
        "thumbnail": "https://www.freetogame.com/g/428/thumbnail.jpg",
        "short_description": "A free to play browser-based city-building strategy game by GameForge.",
        "game_url": "https://www.freetogame.com/open/ikariam",
        "genre": "Strategy",
        "platform": "Web Browser",
        "publisher": "GameForge",
        "developer": "GameForge",
        "release_date": "2008-03-31",
        "freetogame_profile_url": "https://www.freetogame.com/ikariam"
      },
      {
        "id": 303,
        "title": "Saga",
        "thumbnail": "https://www.freetogame.com/g/303/thumbnail.jpg",
        "short_description": "A free-to-play MMORTS that also features city-building and trading card games.",
        "game_url": "https://www.freetogame.com/open/saga",
        "genre": "Strategy",
        "platform": "PC (Windows)",
        "publisher": "Silverlode Interactive",
        "developer": "Silverlode Interactive , Wasatch Games",
        "release_date": "2008-02-26",
        "freetogame_profile_url": "https://www.freetogame.com/saga"
      },
      {
        "id": 351,
        "title": "Grand Prix Racing Online",
        "thumbnail": "https://www.freetogame.com/g/351/thumbnail.jpg",
        "short_description": "A free-to-play web-based motorsport management game.",
        "game_url": "https://www.freetogame.com/open/gpro",
        "genre": "Strategy",
        "platform": "Web Browser",
        "publisher": "GPRO.net",
        "developer": "GPRO.net",
        "release_date": "2006-08-01",
        "freetogame_profile_url": "https://www.freetogame.com/gpro"
      },
      {
        "id": 429,
        "title": "Astro Empires",
        "thumbnail": "https://www.freetogame.com/g/429/thumbnail.jpg",
        "short_description": "A text-based sci-fi strategy and diplomacy MMO Game in a persistent universe.",
        "game_url": "https://www.freetogame.com/open/astro-empires",
        "genre": "Strategy",
        "platform": "Web Browser",
        "publisher": "Cybertopia",
        "developer": "Cybertopia",
        "release_date": "2006-05-00",
        "freetogame_profile_url": "https://www.freetogame.com/astro-empires"
      },
      {
        "id": 431,
        "title": "Imperia Online",
        "thumbnail": "https://www.freetogame.com/g/431/thumbnail.jpg",
        "short_description": "A 2D free-to-play browser-based Medieval MMORTS, Train soldiers and raise an Empire.",
        "game_url": "https://www.freetogame.com/open/imperia-online",
        "genre": "Strategy",
        "platform": "Web Browser",
        "publisher": "Imperia Online Ltd.",
        "developer": "Imperia Online Ltd.",
        "release_date": "2005-08-23",
        "freetogame_profile_url": "https://www.freetogame.com/imperia-online"
      },
      {
        "id": 352,
        "title": "Travian",
        "thumbnail": "https://www.freetogame.com/g/352/thumbnail.jpg",
        "short_description": "A popular browser-based multiplayer online strategy \r\ngame.",
        "game_url": "https://www.freetogame.com/open/travian",
        "genre": "Strategy",
        "platform": "Web Browser",
        "publisher": "Travian Games",
        "developer": "Travian Games",
        "release_date": "2004-09-05",
        "freetogame_profile_url": "https://www.freetogame.com/travian"
      }
    ],
    "MMORPG": [
      {
        "id": 335,
        "title": "Ragnarok Online",
        "thumbnail": "https://www.freetogame.com/g/335/thumbnail.jpg",
        "short_description": "A popular fantasy MMORPG, back to the golden age of MMORPGs.",
        "game_url": "https://www.freetogame.com/open/ragnarok-online",
        "genre": "MMORPG",
        "platform": "PC (Windows)",
        "publisher": "Gravity Interactive ",
        "developer": "Gravity Interactive ",
        "release_date": "2003-06-01",
        "freetogame_profile_url": "https://www.freetogame.com/ragnarok-online"
      },
      {
        "id": 17,
        "title": "Entropia Universe",
        "thumbnail": "https://www.freetogame.com/g/17/thumbnail.jpg",
        "short_description": "A 3D MMO Multi Virtual World Real Cash Economy Experience with RPG elements. ",
        "game_url": "https://www.freetogame.com/open/entropia-universe",
        "genre": "MMORPG",
        "platform": "PC (Windows)",
        "publisher": "MindArk",
        "developer": "MindArk",
        "release_date": "2003-01-30",
        "freetogame_profile_url": "https://www.freetogame.com/entropia-universe"
      },
      {
        "id": 336,
        "title": "Anarchy Online",
        "thumbnail": "https://www.freetogame.com/g/336/thumbnail.jpg",
        "short_description": "A free to play Sci-Fi MMO that has withstood the test of time.",
        "game_url": "https://www.freetogame.com/open/anarchy-online",
        "genre": "MMORPG",
        "platform": "PC (Windows)",
        "publisher": "Funcom",
        "developer": "Funcom",
        "release_date": "2001-06-27",
        "freetogame_profile_url": "https://www.freetogame.com/anarchy-online"
      },
      {
        "id": 251,
        "title": "The Lord of the Rings Online",
        "thumbnail": "https://www.freetogame.com/g/251/thumbnail.jpg",
        "short_description": "A free to play MMORPG set in the world of J.R.R. Tolkien's \r\nclassic fantasy saga.",
        "game_url": "https://www.freetogame.com/open/lotro",
        "genre": "MMORPG",
        "platform": "PC (Windows)",
        "publisher": "Warner Bros. Interactive Entertainment",
        "developer": "Turbine, Inc.",
        "release_date": "2001-04-24",
        "freetogame_profile_url": "https://www.freetogame.com/lotro"
      },
      {
        "id": 339,
        "title": "Tibia",
        "thumbnail": "https://www.freetogame.com/g/339/thumbnail.jpg",
        "short_description": "A old-school free-to-play massively multiplayer online \r\nrole-playing game.",
        "game_url": "https://www.freetogame.com/open/tibia",
        "genre": "MMORPG",
        "platform": "PC (Windows)",
        "publisher": "CipSoft",
        "developer": "CipSoft",
        "release_date": "1997-01-07",
        "freetogame_profile_url": "https://www.freetogame.com/tibia"
      }
    ],
    "Fighting": [
      {
        "id": 274,
        "title": "GetAmped 2",
        "thumbnail": "https://www.freetogame.com/g/274/thumbnail.jpg",
        "short_description": "A free to play fighting MMO, experience frantic battles up to 20 players.",
        "game_url": "https://www.freetogame.com/open/getamped-2",
        "genre": "Fighting",
        "platform": "PC (Windows)",
        "publisher": "CyberStep",
        "developer": "CyberStep",
        "release_date": "2010-12-16",
        "freetogame_profile_url": "https://www.freetogame.com/getamped-2"
      },
      {
        "id": 311,
        "title": "Rumble Fighter",
        "thumbnail": "https://www.freetogame.com/g/311/thumbnail.jpg",
        "short_description": "A free to play Fighting MMO, test your skills!",
        "game_url": "https://www.freetogame.com/open/rumble-fighter",
        "genre": "Fighting",
        "platform": "PC (Windows)",
        "publisher": "RedFox Games",
        "developer": "Nimonix",
        "release_date": "2007-08-02",
        "freetogame_profile_url": "https://www.freetogame.com/rumble-fighter"
      }
    ],
    "Action RPG": [
      {
        "id": 475,
        "title": "Genshin Impact",
        "thumbnail": "https://www.freetogame.com/g/475/thumbnail.jpg",
        "short_description": "If you’ve been looking for a game to scratch that open-world action RPG itch, one with perhaps a bit of Asian flair, then you’re going to want to check out miHoYo’s Genshin Impact.",
        "game_url": "https://www.freetogame.com/open/genshin-impact",
        "genre": "Action RPG",
        "platform": "PC (Windows)",
        "publisher": "miHoYo",
        "developer": "miHoYo",
        "release_date": "2020-09-28",
        "freetogame_profile_url": "https://www.freetogame.com/genshin-impact"
      }
    ],
    "Battle Royale": [
      {
        "id": 523,
        "title": "Fall Guys",
        "thumbnail": "https://www.freetogame.com/g/523/thumbnail.jpg",
        "short_description": "Play the most competitive massively multiplayer party royale game featuring beans ever for free on a variety of platforms. ",
        "game_url": "https://www.freetogame.com/open/fall-guys",
        "genre": "Battle Royale",
        "platform": "PC (Windows)",
        "publisher": "Mediatonic",
        "developer": "Mediatonic",
        "release_date": "2020-08-04",
        "freetogame_profile_url": "https://www.freetogame.com/fall-guys"
      },
      {
        "id": 539,
        "title": "Deathverse: Let It Die",
        "thumbnail": "https://www.freetogame.com/g/539/thumbnail.jpg",
        "short_description": "A game of survival where contestants are pit against each other in a life or death game show.",
        "game_url": "https://www.freetogame.com/open/deathverse-let-it-die",
        "genre": "Battle Royale",
        "platform": "PC (Windows)",
        "publisher": "Supertrick Games, Inc.",
        "developer": "GungHo Online Entertianment, Inc.",
        "release_date": "2022-09-28",
        "freetogame_profile_url": "https://www.freetogame.com/deathverse-let-it-die"
      },
      {
        "id": 530,
        "title": "Rumbleverse",
        "thumbnail": "https://www.freetogame.com/g/530/thumbnail.jpg",
        "short_description": "Take 40 people, throw them into a city, give them weapons and let them fight it out. That’s the recipe for Iron Galaxy Studios’ new free-to-play Brawler Royale Rumbleverse.",
        "game_url": "https://www.freetogame.com/open/rumbleverse",
        "genre": "Battle Royale",
        "platform": "PC (Windows)",
        "publisher": "Epic Games Publishing",
        "developer": "Iron Galaxy Studios",
        "release_date": "2022-08-11",
        "freetogame_profile_url": "https://www.freetogame.com/rumbleverse"
      },
      {
        "id": 473,
        "title": "Spellbreak",
        "thumbnail": "https://www.freetogame.com/g/473/thumbnail.jpg",
        "short_description": "Spellbreak is a multiplayer, multi-platform battle-royale where player take on the role of a “battlemage” mastering elemental magic and using spells to compete against other players.",
        "game_url": "https://www.freetogame.com/open/spellbreak",
        "genre": "Battle Royale",
        "platform": "PC (Windows)",
        "publisher": "Proletariat",
        "developer": "Proletariat",
        "release_date": "2020-09-04",
        "freetogame_profile_url": "https://www.freetogame.com/spellbreak"
      },
      {
        "id": 459,
        "title": "Bombergrounds: Battle Royale",
        "thumbnail": "https://www.freetogame.com/g/459/thumbnail.jpg",
        "short_description": "A free-to-play massively multiplayer battle Royale game inspired by the old-shool Bomberman games!",
        "game_url": "https://www.freetogame.com/open/bombergrounds-battle-royale",
        "genre": "Battle Royale",
        "platform": "PC (Windows)",
        "publisher": "Giant Duck Games",
        "developer": "Giant Duck Games",
        "release_date": "2020-03-07",
        "freetogame_profile_url": "https://www.freetogame.com/bombergrounds-battle-royale"
      }
    ],
    "MOBA": [
      {
        "id": 94,
        "title": "Battlerite",
        "thumbnail": "https://www.freetogame.com/g/94/thumbnail.jpg",
        "short_description": "A free-to-play team arena brawler developed by Stunlock Studios. Players play as one of several available champions on teams in 2v2 or 3v3 matches. ",
        "game_url": "https://www.freetogame.com/open/battlerite",
        "genre": "MOBA",
        "platform": "PC (Windows)",
        "publisher": "Stunlock Studios",
        "developer": "Stunlock Studios",
        "release_date": "2016-09-21",
        "freetogame_profile_url": "https://www.freetogame.com/battlerite"
      },
      {
        "id": 168,
        "title": "Heroes of the Storm",
        "thumbnail": "https://www.freetogame.com/g/168/thumbnail.jpg",
        "short_description": "A free to play MOBA developed by Blizzard Entertainment.",
        "game_url": "https://www.freetogame.com/open/heroes-of-the-storm",
        "genre": "MOBA",
        "platform": "PC (Windows)",
        "publisher": " Blizzard Entertainment",
        "developer": " Blizzard Entertainment",
        "release_date": "2015-06-02",
        "freetogame_profile_url": "https://www.freetogame.com/heroes-of-the-storm"
      },
      {
        "id": 229,
        "title": "Dota 2",
        "thumbnail": "https://www.freetogame.com/g/229/thumbnail.jpg",
        "short_description": "Valve's premiere competitive free to play MOBA.",
        "game_url": "https://www.freetogame.com/open/dota-2",
        "genre": "MOBA",
        "platform": "PC (Windows)",
        "publisher": "Valve",
        "developer": "Valve",
        "release_date": "2013-07-09",
        "freetogame_profile_url": "https://www.freetogame.com/dota-2"
      },
      {
        "id": 231,
        "title": "Panzar",
        "thumbnail": "https://www.freetogame.com/g/231/thumbnail.jpg",
        "short_description": "A free-to-play multiplayer third-person shooter with \r\nrpg elements and CryEngine 3 powered \r\ngraphics.",
        "game_url": "https://www.freetogame.com/open/panzar",
        "genre": "MOBA",
        "platform": "PC (Windows)",
        "publisher": "Panzar",
        "developer": "Troxit Service",
        "release_date": "2013-04-12",
        "freetogame_profile_url": "https://www.freetogame.com/panzar"
      },
      {
        "id": 273,
        "title": "Bloodline Champions",
        "thumbnail": "https://www.freetogame.com/g/273/thumbnail.jpg",
        "short_description": "Free-to-Play Moba game where players engage in short battles of up to ten players divided into two teams.",
        "game_url": "https://www.freetogame.com/open/bloodline-champions",
        "genre": "MOBA",
        "platform": "PC (Windows)",
        "publisher": "Stunlock Studios",
        "developer": "Stunlock Studios",
        "release_date": "2011-01-13",
        "freetogame_profile_url": "https://www.freetogame.com/bloodline-champions"
      },
      {
        "id": 286,
        "title": "League of Legends",
        "thumbnail": "https://www.freetogame.com/g/286/thumbnail.jpg",
        "short_description": "A free-to-play MOBA game, and one of the most played pc game in the world.",
        "game_url": "https://www.freetogame.com/open/league-of-legends",
        "genre": "MOBA",
        "platform": "PC (Windows)",
        "publisher": "Riot Games",
        "developer": "Riot Games",
        "release_date": "2009-10-27",
        "freetogame_profile_url": "https://www.freetogame.com/league-of-legends"
      }
    ],
    "Card Game": [
      {
        "id": 163,
        "title": "Card Hunter",
        "thumbnail": "https://www.freetogame.com/g/163/thumbnail.jpg",
        "short_description": "A free online collectible card game which blends together role-playing, card play and tactical combat. ",
        "game_url": "https://www.freetogame.com/open/card-hunter",
        "genre": "Card Game",
        "platform": "PC (Windows), Web Browser",
        "publisher": "Blue Manchu",
        "developer": "Blue Manchu",
        "release_date": "2015-07-14",
        "freetogame_profile_url": "https://www.freetogame.com/card-hunter"
      },
      {
        "id": 187,
        "title": "Pox Nora",
        "thumbnail": "https://www.freetogame.com/g/187/thumbnail.jpg",
        "short_description": "A multiplayer online game that combines a collectible card game with a turn-based strategy game.",
        "game_url": "https://www.freetogame.com/open/pox-nora",
        "genre": "Card Game",
        "platform": "PC (Windows)",
        "publisher": "Desert Owl Games LLC ",
        "developer": "Desert Owl Games LLC ",
        "release_date": "2014-10-15",
        "freetogame_profile_url": "https://www.freetogame.com/pox-nora"
      },
      {
        "id": 193,
        "title": "Infinity Wars",
        "thumbnail": "https://www.freetogame.com/g/193/thumbnail.jpg",
        "short_description": "A MMO trading card game, Build up your decks and customize them with tons of factional cards! ",
        "game_url": "https://www.freetogame.com/open/infinity-wars",
        "genre": "Card Game",
        "platform": "PC (Windows)",
        "publisher": "Lightmare Studios",
        "developer": "Lightmare Studios",
        "release_date": "2014-09-05",
        "freetogame_profile_url": "https://www.freetogame.com/infinity-wars"
      },
      {
        "id": 215,
        "title": "Hex",
        "thumbnail": "https://www.freetogame.com/g/215/thumbnail.jpg",
        "short_description": "HEX combines roleplaying aspects of a MMO with the collectible and strategic gameplay of a Trading Card Game.",
        "game_url": "https://www.freetogame.com/open/hex",
        "genre": "Card Game",
        "platform": "PC (Windows)",
        "publisher": "Hex Entertainment, Gameforge",
        "developer": "Cryptozoic Entertainment",
        "release_date": "2014-04-11",
        "freetogame_profile_url": "https://www.freetogame.com/hex"
      },
      {
        "id": 220,
        "title": "Hearthstone: Heroes of Warcraft",
        "thumbnail": "https://www.freetogame.com/g/220/thumbnail.jpg",
        "short_description": "Blizzard's free-to-play collectible card game that \r\ndraws its inspiration from World of Warcraft. ",
        "game_url": "https://www.freetogame.com/open/hearthstone-heroes-warcraft",
        "genre": "Card Game",
        "platform": "PC (Windows)",
        "publisher": "Blizzard Entertainment",
        "developer": "Blizzard Entertainment",
        "release_date": "2014-01-21",
        "freetogame_profile_url": "https://www.freetogame.com/hearthstone-heroes-warcraft"
      },
      {
        "id": 240,
        "title": "Epic Cards Battle",
        "thumbnail": "https://www.freetogame.com/g/240/thumbnail.jpg",
        "short_description": "A free to play online strategic trading card game with dozens of cards and five factions. ",
        "game_url": "https://www.freetogame.com/open/epic-card-battle",
        "genre": "Card Game",
        "platform": "PC (Windows)",
        "publisher": "momoStorm Entertainment",
        "developer": "momoStorm",
        "release_date": "2013-01-29",
        "freetogame_profile_url": "https://www.freetogame.com/epic-card-battle"
      },
      {
        "id": 430,
        "title": "Urban Rivals",
        "thumbnail": "https://www.freetogame.com/g/430/thumbnail.jpg",
        "short_description": "A free to play browser based card-game with a high player base and comic-book inspired world!",
        "game_url": "https://www.freetogame.com/open/urban-rivals",
        "genre": "Card Game",
        "platform": "Web Browser",
        "publisher": "Boostr ",
        "developer": "Acute Mobile",
        "release_date": "2006-01-17",
        "freetogame_profile_url": "https://www.freetogame.com/urban-rivals"
      }
    ],
    "Sports": [
      {
        "id": 326,
        "title": "Shot Online",
        "thumbnail": "https://www.freetogame.com/g/326/thumbnail.jpg",
        "short_description": "A free to play Golfing MMO that any golf lover will enjoy to play!",
        "game_url": "https://www.freetogame.com/open/shot-online",
        "genre": "Sports",
        "platform": "PC (Windows)",
        "publisher": "GamesCampus",
        "developer": "OnNet Co. Ltd.",
        "release_date": "2004-11-30",
        "freetogame_profile_url": "https://www.freetogame.com/shot-online"
      }
    ],
    "MMOFPS": [
      {
        "id": 533,
        "title": "A.V.A Global",
        "thumbnail": "https://www.freetogame.com/g/533/thumbnail.jpg",
        "short_description": "A.V.A is a free-to-play online first-person shooter with multiple game modes, unique customizations, as well as PvP and PvE gameplay.",
        "game_url": "https://www.freetogame.com/open/ava",
        "genre": "MMOFPS",
        "platform": "PC (Windows)",
        "publisher": "NEOWIZ",
        "developer": "NEOWIZ",
        "release_date": "2022-08-24",
        "freetogame_profile_url": "https://www.freetogame.com/ava"
      }
    ],
    "Moba": [
      {
        "id": 513,
        "title": "Super Squad",
        "thumbnail": "https://www.freetogame.com/g/513/thumbnail.jpg",
        "short_description": "Prepare yourself. It’s time for Mayhem. Super Squad is a multi-player online shoot-’em-up (or MOSH)!",
        "game_url": "https://www.freetogame.com/open/super-squad",
        "genre": "Moba",
        "platform": "PC (Windows)",
        "publisher": "Bad Fox Studios",
        "developer": "Bad Fox Studios",
        "release_date": "2021-06-25",
        "freetogame_profile_url": "https://www.freetogame.com/super-squad"
      }
    ],
    "MMO": [
      {
        "id": 498,
        "title": "Blankos Block Party",
        "thumbnail": "https://www.freetogame.com/g/498/thumbnail.jpg",
        "short_description": "What happens when you take the vinyl collectible toy experience and combine it with an open-world multiplayer game? You get Blankos Block Party!\r\n",
        "game_url": "https://www.freetogame.com/open/blankos",
        "genre": "MMO",
        "platform": "PC (Windows)",
        "publisher": "Third Kind Games",
        "developer": "Mythical Games Inc",
        "release_date": "2020-12-11",
        "freetogame_profile_url": "https://www.freetogame.com/blankos"
      },
      {
        "id": 501,
        "title": "Fer.al",
        "thumbnail": "https://www.freetogame.com/g/501/thumbnail.jpg",
        "short_description": "If you’ve ever wanted to be a creature of myth and hang out with other mytical creatures, Wildworks’ Fer.al can help you live the dream.",
        "game_url": "https://www.freetogame.com/open/Feral",
        "genre": "MMO",
        "platform": "PC (Windows)",
        "publisher": "Wildworks",
        "developer": "Wildworks",
        "release_date": "2019-12-13",
        "freetogame_profile_url": "https://www.freetogame.com/Feral"
      },
      {
        "id": 196,
        "title": "Cubic Castles",
        "thumbnail": "https://www.freetogame.com/g/196/thumbnail.jpg",
        "short_description": "A free to play 3D Platforming and a open world building game.",
        "game_url": "https://www.freetogame.com/open/cubic-castles",
        "genre": "MMO",
        "platform": "PC (Windows)",
        "publisher": "Cosmic Cow LLC",
        "developer": "Cosmic Cow LLC",
        "release_date": "2014-08-13",
        "freetogame_profile_url": "https://www.freetogame.com/cubic-castles"
      },
      {
        "id": 198,
        "title": "Creativerse",
        "thumbnail": "https://www.freetogame.com/g/198/thumbnail.jpg",
        "short_description": "Playful Corporation enters the sandbox, voxel world with their free-to-play title Creativers.",
        "game_url": "https://www.freetogame.com/open/creativerse",
        "genre": "MMO",
        "platform": "PC (Windows)",
        "publisher": "Playful Corporation",
        "developer": "Playful Corporation",
        "release_date": "2014-08-12",
        "freetogame_profile_url": "https://www.freetogame.com/creativerse"
      },
      {
        "id": 203,
        "title": "Robocraft",
        "thumbnail": "https://www.freetogame.com/g/203/thumbnail.jpg",
        "short_description": "A free-to-play MMO sandbox building game! ",
        "game_url": "https://www.freetogame.com/open/robocraft",
        "genre": "MMO",
        "platform": "PC (Windows)",
        "publisher": "Freejam",
        "developer": "Freejam",
        "release_date": "2014-07-08",
        "freetogame_profile_url": "https://www.freetogame.com/robocraft"
      },
      {
        "id": 16,
        "title": "Roblox",
        "thumbnail": "https://www.freetogame.com/g/16/thumbnail.jpg",
        "short_description": "A free to play sandbox MMO with lots of creation options.",
        "game_url": "https://www.freetogame.com/open/roblox",
        "genre": "MMO",
        "platform": "PC (Windows)",
        "publisher": "Roblox Corporation",
        "developer": "Roblox Corporation",
        "release_date": "2006-12-22",
        "freetogame_profile_url": "https://www.freetogame.com/roblox"
      }
    ],
    "Racing": [
      {
        "id": 93,
        "title": "Riding Club Championships",
        "thumbnail": "https://www.freetogame.com/g/93/thumbnail.jpg",
        "short_description": "An online competitive horse riding game inspired by traditional equestrian disciplines. ",
        "game_url": "https://www.freetogame.com/open/riding-club-championships",
        "genre": "Racing",
        "platform": "PC (Windows)",
        "publisher": "Artplant",
        "developer": "Artplant",
        "release_date": "2016-09-27",
        "freetogame_profile_url": "https://www.freetogame.com/riding-club-championships"
      },
      {
        "id": 121,
        "title": "Forza Motorsport 6: Apex",
        "thumbnail": "https://www.freetogame.com/g/121/thumbnail.jpg",
        "short_description": "A free-to-play MMO racing game that comes from makers of one of the most popular video game racing series ever. ",
        "game_url": "https://www.freetogame.com/open/forza-motorsport-6-apex",
        "genre": "Racing",
        "platform": "PC (Windows)",
        "publisher": "Microsoft",
        "developer": "Turn 10",
        "release_date": "2015-09-15",
        "freetogame_profile_url": "https://www.freetogame.com/forza-motorsport-6-apex"
      }
    ],
    "Social": [
      {
        "id": 125,
        "title": "Atom Universe",
        "thumbnail": "https://www.freetogame.com/g/125/thumbnail.jpg",
        "short_description": "A free-to-play multiplayer online social Virtual World set in a theme park.",
        "game_url": "https://www.freetogame.com/open/atom-universe",
        "genre": "Social",
        "platform": "PC (Windows)",
        "publisher": "Atom Republic",
        "developer": "Atom Republic",
        "release_date": "2016-02-27",
        "freetogame_profile_url": "https://www.freetogame.com/atom-universe"
      },
      {
        "id": 292,
        "title": "5Street",
        "thumbnail": "https://www.freetogame.com/g/292/thumbnail.jpg",
        "short_description": "A free-to-play dancing MMO and a unique social experience.",
        "game_url": "https://www.freetogame.com/open/5street",
        "genre": "Social",
        "platform": "PC (Windows)",
        "publisher": "Snail Games",
        "developer": "Snail Games",
        "release_date": "2011-11-11",
        "freetogame_profile_url": "https://www.freetogame.com/5street"
      },
      {
        "id": 314,
        "title": "Audition Online",
        "thumbnail": "https://www.freetogame.com/g/314/thumbnail.jpg",
        "short_description": "A 3D rhythm MMO, Compete against other players in dance competitions.",
        "game_url": "https://www.freetogame.com/open/audition-online",
        "genre": "Social",
        "platform": "PC (Windows)",
        "publisher": "Redbana Corporation",
        "developer": "T3 Entertainment",
        "release_date": "2007-04-02",
        "freetogame_profile_url": "https://www.freetogame.com/audition-online"
      },
      {
        "id": 18,
        "title": "Second Life",
        "thumbnail": "https://www.freetogame.com/g/18/thumbnail.jpg",
        "short_description": "A free to play 3D online virtual world with a huge reputation! ",
        "game_url": "https://www.freetogame.com/open/second-life",
        "genre": "Social",
        "platform": "PC (Windows)",
        "publisher": "Linden Lab",
        "developer": "Linden Lab",
        "release_date": "2003-06-23",
        "freetogame_profile_url": "https://www.freetogame.com/second-life"
      },
      {
        "id": 432,
        "title": "Habbo",
        "thumbnail": "https://www.freetogame.com/g/432/thumbnail.jpg",
        "short_description": "One of the largest and most popular Social MMO.",
        "game_url": "https://www.freetogame.com/open/habbo",
        "genre": "Social",
        "platform": "Web Browser",
        "publisher": "Sulake Corporation",
        "developer": "Sulake Corporation",
        "release_date": "2001-09-26",
        "freetogame_profile_url": "https://www.freetogame.com/habbo"
      }
    ],
    " MMORPG": [
      {
        "id": 386,
        "title": "Aberoth",
        "thumbnail": "https://www.freetogame.com/g/386/thumbnail.jpg",
        "short_description": "A free to play 8-bit MMORPG with retro graphics and MUD-like interface.",
        "game_url": "https://www.freetogame.com/open/aberoth",
        "genre": " MMORPG",
        "platform": "Web Browser",
        "publisher": "Jarbit",
        "developer": "Jarbit",
        "release_date": "2015-07-17",
        "freetogame_profile_url": "https://www.freetogame.com/aberoth"
      }
    ],
    "Fantasy": [
      {
        "id": 179,
        "title": "Transformice",
        "thumbnail": "https://www.freetogame.com/g/179/thumbnail.jpg",
        "short_description": "A cute little free-to-play MMO platformer.",
        "game_url": "https://www.freetogame.com/open/transformice",
        "genre": "Fantasy",
        "platform": "PC (Windows), Web Browser",
        "publisher": "Atelier 801",
        "developer": "Atelier 801",
        "release_date": "2015-01-30",
        "freetogame_profile_url": "https://www.freetogame.com/transformice"
      }
    ]
  }